# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('more', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Old',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50)),
                ('reason', models.CharField(blank=True, max_length=50)),
                ('done', models.BooleanField(default=False)),
                ('daily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.History')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=50)),
                ('future', models.BooleanField(default=False)),
            ],
        ),
    ]
