# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='status',
            field=models.CharField(default='low', max_length=10),
            preserve_default=False,
        ),
    ]
