# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_history_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=25)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
