# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160911_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='desc',
            field=models.CharField(default='desc', max_length=100),
            preserve_default=False,
        ),
    ]
