# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_notes_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
