# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-29 16:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('comment_date', models.DateField(blank=True, null=True)),
                ('like', models.IntegerField(default=0)),
                ('unlike', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ExtUser',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('sex', models.CharField(blank=True, max_length=2, null=True)),
                ('autograph', models.CharField(blank=True, max_length=50, null=True)),
                ('greet', models.CharField(blank=True, max_length=50, null=True)),
                ('labels', models.CharField(blank=True, max_length=50, null=True)),
                ('register_date', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Love',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('douban_id', models.IntegerField(primary_key=True, serialize=False)),
                ('film_name', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=100)),
                ('film_length', models.IntegerField()),
                ('area', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=100)),
                ('actors', models.TextField()),
                ('labels', models.CharField(max_length=30)),
                ('douban_rate', models.FloatField()),
                ('douban_comment_num', models.IntegerField()),
                ('detail_info', models.TextField()),
                ('img_name', models.CharField(max_length=15)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='love',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recSys.Movie'),
        ),
        migrations.AddField(
            model_name='love',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recSys.Movie'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
